# Generated by Django 5.1.1 on 2025-05-19 00:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0003_scrap_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='scraping.scrap')),
                ('summary', models.TextField()),
                ('summaryDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
